//
// Created by yretenai on 2020-06-09.
//

#ifndef FMT_DRAGON_ACTORMATERIALATTRIBUTESET_H
#define FMT_DRAGON_ACTORMATERIALATTRIBUTESET_H

class ActorMaterialAttributeSet {};

#endif // FMT_DRAGON_ACTORMATERIALATTRIBUTESET_H
