//
// Created by yretenai on 2020-06-15.
//

#ifndef DRAGON_WAROFDRAGON_GLOBALS_H
#define DRAGON_WAROFDRAGON_GLOBALS_H

#define DRAGON_WAROFDRAGON_VERSION "1.0.0"

#endif // DRAGON_WAROFDRAGON_GLOBALS_H
